version: "3"

tasks:
  sync-all:
    desc: Sync uv environment and install pyzed
    cmds:
      - uv sync --extra dev
      - uv run --script scripts/install_pyzed.py

  record:
    desc: Record stereo pairs from ZED camera to MCAP
    cmd: uv run python scripts/record_pyzed.py {{.CLI_ARGS}}

  test:
    desc: Run all tests
    cmd: uv run pytest -s tests {{.CLI_ARGS}}

  test-gpu:
    desc: Test to make sure that the current setup works
    cmd: uv run pytest tests/test_setup.py

  test-camera:
    desc: Test to make sure that the camera connection works
    cmd: uv run pytest -m "" tests/test_setup.py::test_camera
